"use client";
import { useState } from "react";
import { matchCategoryLabel } from "@/lib/localization";
import type { MatchCategory } from "@/domain/models";
export interface AnalysisReviewView { id: string; positionId: string; doublecheckOutcome: string; status: string; agentEvidence: Record<string, unknown>; independentEvidence: Record<string, unknown>; decisionReason: string | null; decidedBy: string | null; decidedAt: string | null; }
export function AnalysisReviewQueue({ initialReviews }: { initialReviews: AnalysisReviewView[] }) {
  const [reviews, setReviews] = useState(initialReviews); const [reason, setReason] = useState<Record<string, string>>({}); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState("");
  async function decide(id: string, decision: "CONFIRMED" | "REJECTED" | "RETURNED") { setBusy(id); setError(""); try { const response = await fetch(`/api/analysis-reviews/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, reason: reason[id] ?? "" }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "Не удалось сохранить решение"); setReviews((current) => current.map((item) => item.id === id ? payload.review : item)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Не удалось сохранить решение"); } finally { setBusy(null); } }
  const doublechecked = reviews.filter((review) => review.doublecheckOutcome === "CONFIRMED_FOR_HUMAN_REVIEW").length; const decided = reviews.filter((review) => ["CONFIRMED", "REJECTED", "RETURNED"].includes(review.status)).length;
  return <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm" aria-labelledby="review-queue-title"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-teal-700">Даблчекер МТР</p><h2 id="review-queue-title" className="mt-1 text-lg font-semibold">Очередь экспертной проверки</h2><p className="mt-1 text-sm text-slate-500">Даже точное совпадение 100% после независимой проверки ожидает решения человека. Система не выполняет закупку, резерв или договорное решение.</p></div><div className="text-right text-xs text-slate-500"><p>Готово к визированию: <b className="text-slate-900">{doublechecked}</b></p><p className="mt-1">Решений человека: <b className="text-slate-900">{decided}</b></p><p className="mt-1">Калибровка основана на: <b className="text-slate-900">{decided} решениях</b></p></div></div>{error && <p role="alert" className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-4 space-y-3">{reviews.map((review) => <article key={review.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono text-xs font-semibold text-teal-800">{String(review.agentEvidence.positionCode ?? review.positionId)}</p><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800">{statusLabel(review.status)}</span></div><p className="mt-2 text-xs font-medium text-slate-700">{outcomeLabel(review.doublecheckOutcome)}</p><div className="mt-3 grid gap-3 text-xs text-slate-600 md:grid-cols-2"><Evidence title="Вывод МТР Агента" data={review.agentEvidence} /><Evidence title="Независимые доказательства Даблчекера" data={review.independentEvidence} /></div><label className="mt-3 block text-xs font-medium text-slate-600">Причина решения<textarea value={reason[review.id] ?? review.decisionReason ?? ""} onChange={(event) => setReason((current) => ({ ...current, [review.id]: event.target.value }))} className="mt-1 min-h-20 w-full rounded-md border border-slate-300 p-2 text-sm" placeholder="Обоснование обязательно" /></label><div className="mt-3 flex flex-wrap gap-2"><Action disabled={busy === review.id} onClick={() => decide(review.id, "CONFIRMED")}>Подтвердить</Action><Action disabled={busy === review.id} onClick={() => decide(review.id, "REJECTED")}>Отклонить</Action><Action disabled={busy === review.id} onClick={() => decide(review.id, "RETURNED")}>Вернуть на уточнение</Action></div>{review.decidedBy && <p className="mt-3 text-xs text-slate-500">Последнее решение: {review.decidedBy}{review.decidedAt ? ` · ${new Date(review.decidedAt).toLocaleString("ru-RU")}` : ""}</p>}</article>)}{reviews.length === 0 && <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">Результатов для визирования пока нет.</p>}</div></section>;
}
function Evidence({ title, data }: { title: string; data: Record<string, unknown> }) { return <div className="rounded-md bg-slate-50 p-3"><p className="font-semibold text-slate-800">{title}</p>{Object.entries(data).slice(0, 6).map(([key, value]) => <p key={key} className="mt-1"><span className="text-slate-400">{evidenceLabel(key)}:</span> {evidenceValue(key, value)}</p>)}</div>; }
function Action({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button type="button" className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold hover:bg-slate-50 disabled:opacity-50" {...props}>{children}</button>; }
function statusLabel(status: string) { return ({ PENDING: "Ожидает решения", CONFIRMED: "Подтверждено экспертом", REJECTED: "Отклонено", RETURNED: "На уточнении" } as Record<string, string>)[status] ?? status; }
function outcomeLabel(outcome: string) { return ({ CONFIRMED_FOR_HUMAN_REVIEW: "Подтверждено для визирования человеком", HUMAN_REVIEW_REQUIRED: "Требуется решение человека", INSUFFICIENT_DATA: "Недостаточно данных: требуется человек" } as Record<string, string>)[outcome] ?? "Требуется решение человека"; }
function evidenceLabel(key: string) { return ({ positionCode: "Код позиции", category: "Категория", score: "Совпадение", materialCode: "Код материала", requiresHumanReview: "Требуется проверка", rule: "Правило", categoryEqual: "Категория точная", scoreEqual100: "Совпадение 100%", humanReviewFlagAbsent: "Нет дополнительных ограничений", source: "Источник" } as Record<string, string>)[key] ?? "Признак"; }
function evidenceValue(key: string, value: unknown): string {
  if (key === "category" && isMatchCategory(value)) return matchCategoryLabel(value);
  if (key === "rule" && typeof value === "string") {
    return value.replace(/\bEXACT\b/gu, "точная категория");
  }
  if (typeof value === "boolean") return value ? "Да" : "Нет";
  if (Array.isArray(value)) return value.map((item) => evidenceValue(key, item)).join(", ");
  if (value === null || value === undefined) return "—";
  if (key === "source" && typeof value === "string") {
    return ({ SAP: "SAP S/4HANA", APPIUS: "Appius PLM", MTR_AGENT: "МТР Агент", DOUBLECHECKER: "Даблчекер" } as Record<string, string>)[value] ?? "Подтверждённый источник";
  }
  if (!["positionCode", "materialCode"].includes(key) && typeof value === "string" && /^[A-Z][A-Z0-9_]+$/u.test(value)) {
    return "Техническое значение скрыто";
  }
  return String(value);
}
function isMatchCategory(value: unknown): value is MatchCategory { return typeof value === "string" && ["EXACT", "LIKELY", "REVIEW", "NO_MATCH"].includes(value); }
